import { createFileRoute, Link } from '@tanstack/react-router';
import { useState } from 'react';
import { ChevronRight, Plus, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Heading, Empty } from '@/components/common';
import { Workspace } from '@/components/workspace';
import { PatientForm } from '@/components/forms';
import { StatusBadge } from '@/components/status-badge';
import { useApp } from '@/lib/app-context';
import { dateOf, nameOf, statusOf } from '@/lib/fax';
export const Route = createFileRoute('/patients')({head:()=>({meta:[{title:'Patients | NYC Home Rehab Fax Tracker'},{name:'description',content:'Search and manage patient fax tracking records.'},{property:'og:title',content:'Patients | NYC Home Rehab Fax Tracker'},{property:'og:description',content:'Authorized patient records and document history.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary'}]}),component:Patients});
function Patients(){const {patients,documents,attempts,search,role}=useApp();const [local,setLocal]=useState('');const [filter,setFilter]=useState('All');const [show,setShow]=useState(false);const list=patients.filter(p=>(filter==='All'||p.status===filter)&&`${nameOf(p)} ${p.patient_id} ${p.insurance} ${p.referring_physician}`.toLowerCase().includes(`${search} ${local}`.trim().toLowerCase()) );return <Workspace><Heading title="Patients" subtitle={`${patients.length} patient records · Patient-centered fax tracking`} action={role==='admin'?<Button onClick={()=>setShow(true)}><Plus/> Add Patient</Button>:undefined}/><div className="mb-5 flex flex-wrap items-center gap-3"><div className="relative w-full max-w-xs"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><input className="field pl-9" placeholder="Search patient name..." value={local} onChange={e=>setLocal(e.target.value)}/></div><div className="flex gap-1 rounded border bg-card p-1">{['All','Active','Inactive','Discharged','Archived'].map(v=><Button key={v} size="sm" variant={filter===v?'secondary':'ghost'} onClick={()=>setFilter(v)}>{v}</Button>)}</div></div><div className="table-wrap">{list.length?<table className="data-table"><thead><tr><th>Patient Name</th><th>Patient ID</th><th>DOB</th><th>Phone</th><th>Insurance</th><th>Referring MD</th><th>Documents</th><th>Pending</th><th>Last Fax Activity</th><th>Status</th><th>Actions</th></tr></thead><tbody>{list.map(p=>{const ds=documents.filter(d=>d.patient_id===p.id);return <tr key={p.id}><td><Link to="/patients/$patientId" params={{patientId:p.id}} className="font-bold text-primary hover:underline">{nameOf(p)}</Link>{p.is_demo&&<span className="ml-2 text-[9px] font-bold text-muted-foreground">DEMO</span>}</td><td className="text-muted-foreground">{p.patient_id}</td><td>{dateOf(p.date_of_birth)}</td><td>{p.phone||'—'}</td><td>{p.insurance||'—'}</td><td>{p.referring_physician||'—'}</td><td>{ds.length}</td><td>{ds.filter(d=>['Draft','Pending','Failed','Awaiting Response','Awaiting Upload'].includes(statusOf(d,attempts))).length}</td><td>{dateOf(ds[0]?.created_at)}</td><td><StatusBadge status={p.status}/></td><td><Button asChild variant="ghost" size="icon" title="Open patient"><Link to="/patients/$patientId" params={{patientId:p.id}}><ChevronRight/></Link></Button></td></tr>})}</tbody></table>:<Empty text="No patients match your search."/>}</div>{show&&<PatientForm onClose={()=>setShow(false)}/>}</Workspace>}
