import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Workspace } from '@/components/workspace';
import { Heading, Stat, DocumentTable } from '@/components/common';
import { useApp } from '@/lib/app-context';
import { documentTypes, nameOf, statusOf, titleOf, dateOf } from '@/lib/fax';
export const Route = createFileRoute('/reports')({head:()=>({meta:[{title:'Reports | NYC Home Rehab Fax Tracker'},{name:'description',content:'Fax delivery, response, and upload reports for authorized staff.'},{property:'og:title',content:'Reports | NYC Home Rehab Fax Tracker'},{property:'og:description',content:'Review patient fax activity and export reports.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary'}]}),component:Reports});
function Reports(){const {documents,patients,attempts}=useApp();const [range,setRange]=useState('This Month'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[patient,setPatient]=useState('All patients'),[type,setType]=useState('All types');const now=new Date();const threshold=range==='Today'?new Date(now.getFullYear(),now.getMonth(),now.getDate()):range==='This Week'?new Date(now.getFullYear(),now.getMonth(),now.getDate()-now.getDay()):new Date(now.getFullYear(),now.getMonth(),1);const list=documents.filter(d=>(range==='Custom'?(!from||d.created_at.slice(0,10)>=from)&&(!to||d.created_at.slice(0,10)<=to):new Date(d.created_at)>=threshold)&&(patient==='All patients'||d.patient_id===patient)&&(type==='All types'||d.document_type===type));const ids=new Set(list.map(d=>d.id));const ownAttempts=attempts.filter(a=>ids.has(a.document_id));const counts=[['Documents Faxed',list.filter(d=>ownAttempts.some(a=>a.document_id===d.id&&a.status==='Sent Successfully')).length],['Total Attempts',ownAttempts.length],['Successful Faxes',ownAttempts.filter(a=>a.status==='Sent Successfully').length],['Failed Faxes',ownAttempts.filter(a=>!['Pending','Sent Successfully'].includes(a.status)).length],['Documents Received',list.filter(d=>d.received).length],['Awaiting Response',list.filter(d=>statusOf(d,attempts)==='Awaiting Response').length],['Awaiting Upload',list.filter(d=>d.received&&!d.uploaded).length],['Documents Uploaded',list.filter(d=>d.uploaded).length]] as const;
function rowsForExport(){return [['Patient','Patient ID','Document','MD','Recipient','Date Created','Attempts','Status','Received','Uploaded'],...list.map(d=>{const p=patients.find(p=>p.id===d.patient_id);return [p?nameOf(p):'',p?.patient_id??'',titleOf(d),d.md_name??'',d.recipient_name??'',dateOf(d.created_at),String(ownAttempts.filter(a=>a.document_id===d.id).length),statusOf(d,attempts),d.received?'Yes':'No',d.uploaded?'Yes':'No']})];}
function exportCSV(){const rows=rowsForExport();const csv=rows.map(row=>row.map(value=>'"'+String(value).replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=globalThis.document.createElement('a');a.href=url;a.download='fax-report.csv';a.click();URL.revokeObjectURL(url)}
async function exportExcel(){const rows=rowsForExport();const XLSX=await import('xlsx');const workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet(rows),'Fax Report');XLSX.writeFile(workbook,'fax-report.xlsx')}
async function exportPDF(){const {jsPDF}=await import('jspdf');const pdf=new jsPDF({orientation:'landscape'});pdf.setFontSize(16);pdf.text('NYC HOME REHAB · Fax Report',14,18);pdf.setFontSize(9);pdf.text(`${range} · ${list.length} documents`,14,25);let y=35;for(const row of rowsForExport().slice(0,150)){if(y>190){pdf.addPage();y=18}const line=row.map(v=>String(v).slice(0,24)).join('  |  ');pdf.text(line.slice(0,175),14,y);y+=6}pdf.save('fax-report.pdf')}
return <Workspace><Heading title="Reports" subtitle="Fax performance and document workflow" action={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={exportCSV}><Download/> CSV</Button><Button variant="outline" onClick={exportExcel}><Download/> Excel</Button><Button onClick={exportPDF}><Download/> PDF</Button></div>}/><div className="mb-6 flex flex-wrap gap-3"><select className="field w-auto" value={range} onChange={e=>setRange(e.target.value)} aria-label="Date range">{['Today','This Week','This Month','Custom'].map(x=><option key={x}>{x}</option>)}</select>{range==='Custom'&&<><input className="field w-auto" type="date" aria-label="From date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="field w-auto" type="date" aria-label="To date" value={to} onChange={e=>setTo(e.target.value)}/></>}<select className="field w-auto" value={patient} onChange={e=>setPatient(e.target.value)} aria-label="Patient"><option>All patients</option>{patients.map(p=><option key={p.id} value={p.id}>{nameOf(p)}</option>)}</select><select className="field w-auto" value={type} onChange={e=>setType(e.target.value)} aria-label="Document type"><option>All types</option>{documentTypes.map(t=><option key={t}>{t}</option>)}</select></div><div className="mb-8 grid grid-cols-2 gap-3 md:grid-cols-4">{counts.map(([label,value])=><Stat key={label} label={label} value={value}/>)}</div><h2 className="page-title mb-4 text-lg">Report Details</h2><DocumentTable items={list}/></Workspace>}
