import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Workspace } from '@/components/workspace';
import { Heading, Empty } from '@/components/common';
import { useApp } from '@/lib/app-context';
import { supabase } from '@/integrations/supabase/client';
import { dateTimeOf } from '@/lib/fax';
export const Route = createFileRoute('/settings')({head:()=>({meta:[{title:'Settings | NYC Home Rehab Fax Tracker'},{name:'description',content:'Staff access and audit activity for the fax tracker.'},{property:'og:title',content:'Settings | NYC Home Rehab Fax Tracker'},{property:'og:description',content:'Staff settings and audit activity.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary'}]}),component:Settings});
type RoleRow={id:string;user_id:string;role:string};type AuditRow={id:string;user_id:string|null;action:string;description:string|null;created_at:string};
function Settings(){const {user,role,patients}=useApp();const [roles,setRoles]=useState<RoleRow[]>([]),[logs,setLogs]=useState<AuditRow[]>([]),[saving,setSaving]=useState('');useEffect(()=>{if(role==='admin'){void supabase.from('user_roles').select('*').then(({data})=>setRoles(data??[]));void supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(100).then(({data})=>setLogs(data??[]))}},[role]);async function changeRole(id:string,next:'admin'|'staff'){setSaving(id);const {error}=await supabase.from('user_roles').update({role:next}).eq('id',id);setSaving('');if(error){toast.error(error.message);return}setRoles(roles.map(r=>r.id===id?{...r,role:next}:r));toast.success('Staff role updated.')}
return <Workspace><Heading title="Settings" subtitle="Staff access and record activity"/><div className="grid gap-8 xl:grid-cols-2"><section className="rounded-md border bg-card p-6"><h2 className="page-title mb-5 text-lg">Your Account</h2><div className="space-y-4 text-sm"><div><div className="field-label">Email</div><strong>{user.email}</strong></div><div><div className="field-label">Role</div><strong className="capitalize">{role}</strong></div><div><div className="field-label">Account ID</div><span className="break-all text-xs text-muted-foreground">{user.id}</span></div></div><p className="mt-7 border-t pt-5 text-xs leading-5 text-muted-foreground">New accounts require an administrator to assign a staff role before patient records become visible. An administrator must grant access to new accounts.</p></section><section className="rounded-md border bg-card p-6"><h2 className="page-title mb-5 text-lg">Staff Access</h2>{role==='admin'?<div className="space-y-2">{roles.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-2 border-b py-3 text-xs"><div><div className="font-bold">{r.user_id===user.id?'You':`Staff account ${r.user_id.slice(0,8)}`}</div><div className="mt-1 text-muted-foreground">{r.user_id}</div></div><select aria-label="Staff role" className="field w-auto" value={r.role} disabled={saving===r.id||r.user_id===user.id} onChange={e=>changeRole(r.id,e.target.value as 'admin'|'staff')}><option value="admin">Admin</option><option value="staff">Staff</option></select></div>)}<p className="pt-4 text-xs leading-5 text-muted-foreground">Users must create their own account before an administrator can assign access.</p></div>:<p className="text-sm text-muted-foreground">Only administrators can manage staff roles.</p>}</section></div>{role==='admin'&&<section className="mt-8"><h2 className="page-title mb-4 text-lg">Audit Activity</h2><div className="table-wrap">{logs.length?<table className="data-table"><thead><tr><th>Date & time</th><th>User ID</th><th>Action</th><th>Patient</th><th>Document</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{dateTimeOf(l.created_at)}</td><td>{l.user_id?.slice(0,8)??'System'}</td><td className="capitalize">{l.description??l.action.replaceAll('_',' ')}</td><td>{patients.find(p=>p.id===(l as AuditRow&{patient_id?:string}).patient_id)?.patient_id??'—'}</td><td>{(l as AuditRow&{document_id?:string}).document_id?.slice(0,8)??'—'}</td></tr>)}</tbody></table>:<Empty text="No audit activity yet."/>}</div></section>}</Workspace>}
