import { Link, useRouterState } from '@tanstack/react-router';
import { Activity, ChartNoAxesCombined, ChevronLeft, ChevronRight, ClipboardList, FileClock, LogOut, Menu, Search, Settings, Users, X } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
const nav = [{to:'/',label:'Dashboard',icon:Activity},{to:'/patients',label:'Patients',icon:Users},{to:'/fax-tracker',label:'Fax Tracker',icon:FileClock},{to:'/reports',label:'Reports',icon:ChartNoAxesCombined},{to:'/settings',label:'Settings',icon:Settings}] as const;
export function AppShell({ children, email, search, onSearch }: { children: React.ReactNode; email: string; search: string; onSearch: (v:string)=>void }) {
  const [collapsed,setCollapsed] = useState(false); const [mobile,setMobile] = useState(false);
  const path = useRouterState({select:s=>s.location.pathname});
  return <div className="min-h-screen bg-background lg:flex">
    {mobile && <div className="fixed inset-0 z-30 bg-foreground/30 lg:hidden" onClick={()=>setMobile(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex flex-col bg-sidebar text-sidebar-foreground transition-all lg:sticky lg:top-0 lg:h-screen ${collapsed?'lg:w-18':'lg:w-58'} ${mobile?'w-64 translate-x-0':'-translate-x-full lg:translate-x-0'}`}>
      <div className="flex h-20 items-center justify-between border-b border-sidebar-foreground/10 px-5"><div className="flex items-center gap-3 overflow-hidden"><div className="flex size-9 shrink-0 items-center justify-center rounded bg-gold text-sidebar"><ClipboardList size={19}/></div>{!collapsed && <div className="whitespace-nowrap font-display text-[12px] font-extrabold leading-4">NYC HOME REHAB<br/><span className="font-medium text-sidebar-foreground/60">FAX TRACKER</span></div>}</div><Button aria-label="Close menu" size="icon" variant="ghost" className="lg:hidden text-sidebar-foreground" onClick={()=>setMobile(false)}><X/></Button></div>
      <div className="px-3 pt-8"><div className={`px-3 pb-3 text-[10px] font-bold uppercase text-sidebar-foreground/40 ${collapsed?'lg:hidden':''}`}>Workspace</div><nav className="space-y-1">{nav.map(item=><Link key={item.to} to={item.to} title={item.label} onClick={()=>setMobile(false)} className={`flex h-10 items-center gap-3 rounded px-3 text-sm font-medium transition-colors ${path===item.to || (item.to!=='/' && path.startsWith(item.to+'/'))?'bg-sidebar-accent text-sidebar-foreground border-l-2 border-gold':'text-sidebar-foreground/65 hover:bg-sidebar-accent hover:text-sidebar-foreground'}`}><item.icon size={17} className="shrink-0"/>{!collapsed && item.label}</Link>)}</nav></div>
      <div className="mt-auto border-t border-sidebar-foreground/10 p-3"><Button variant="ghost" size="icon" aria-label={collapsed?'Expand sidebar':'Collapse sidebar'} title={collapsed?'Expand sidebar':'Collapse sidebar'} className="hidden text-sidebar-foreground/70 lg:inline-flex" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<ChevronRight/>:<ChevronLeft/>}</Button><Button variant="ghost" className="w-full justify-start text-sidebar-foreground/70 hover:bg-sidebar-accent hover:text-sidebar-foreground" onClick={()=>supabase.auth.signOut()} title="Sign out"><LogOut size={16}/>{!collapsed && 'Sign out'}</Button></div>
    </aside>
    <div className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-16 items-center gap-4 border-b bg-card px-5 lg:px-8"><Button variant="ghost" size="icon" aria-label="Open menu" className="lg:hidden" onClick={()=>setMobile(true)}><Menu/></Button><div className="relative max-w-md flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><input value={search} onChange={e=>onSearch(e.target.value)} placeholder="Search patients, documents, fax numbers..." className="field w-full pl-9" aria-label="Global search" /></div><div className="ml-auto hidden items-center gap-2 border-l pl-5 sm:flex"><span className="flex size-8 items-center justify-center rounded-full bg-secondary text-xs font-bold text-primary">{email.slice(0,1).toUpperCase()}</span><span className="max-w-40 truncate text-xs font-semibold">{email}</span></div></header><main className="mx-auto max-w-[1650px] p-5 lg:p-8">{children}</main></div>
  </div>;
}
