import { Link } from '@tanstack/react-router';
import { ChevronRight, FolderOpen } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { StatusBadge } from './status-badge';
import { useApp } from '@/lib/app-context';
import { dateOf, nameOf, statusOf, titleOf, type Document } from '@/lib/fax';
export function Heading({title,subtitle,action}:{title:string;subtitle?:string;action?:React.ReactNode}){return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h1 className="page-title text-[27px] text-foreground">{title}</h1>{subtitle&&<p className="mt-1 text-sm text-muted-foreground">{subtitle}</p>}</div>{action}</div>}
export function Stat({label,value,note,tone}:{label:string;value:number|string;note?:string;tone?:string}){return <div className="min-w-0 rounded-md border bg-card p-5"><div className="text-xs font-semibold text-muted-foreground">{label}</div><div className={`mt-3 font-display text-[30px] font-extrabold leading-none ${tone??'text-foreground'}`}>{value}</div>{note&&<div className="mt-3 text-[11px] text-muted-foreground">{note}</div>}</div>}
export function Empty({text='No records found.'}:{text?:string}){return <div className="flex flex-col items-center gap-2 py-16 text-center text-sm text-muted-foreground"><FolderOpen size={24}/>{text}</div>}
export function DocumentTable({items,compact=false}:{items:Document[];compact?:boolean}){const {patients,attempts}=useApp();if(!items.length)return <div className="rounded-md border bg-card"><Empty/></div>;return <div className="table-wrap"><table className="data-table"><thead><tr><th>Patient</th><th>Document</th><th>MD</th><th>Recipient</th><th>Date faxed</th><th>Attempts</th><th>Status</th><th>Received</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody>{items.map(d=>{const p=patients.find(p=>p.id===d.patient_id);const own=attempts.filter(a=>a.document_id===d.id);return <tr key={d.id}><td><Link className="font-semibold text-primary hover:underline" to="/patients/$patientId" params={{patientId:d.patient_id}}>{p?nameOf(p):'Unknown'}</Link>{p?.is_demo&&<span className="ml-2 text-[9px] font-bold text-muted-foreground">DEMO</span>}</td><td><Link className="font-semibold hover:text-primary" to="/documents/$documentId" params={{documentId:d.id}}>{titleOf(d)}</Link></td><td>{d.md_name??'—'}</td><td>{d.recipient_name??'—'}</td><td>{dateOf(own.find(a=>a.status==='Sent Successfully')?.attempted_at??own[0]?.attempted_at)}</td><td>{own.length}</td><td><StatusBadge status={statusOf(d,attempts)}/></td><td>{d.received?'Yes':'No'}</td><td>{d.uploaded?'Yes':'No'}</td><td><Button asChild variant="ghost" size="icon" title="Open document"><Link to="/documents/$documentId" params={{documentId:d.id}}><ChevronRight/></Link></Button></td></tr>})}</tbody></table>{compact&&items.length>8&&<div className="border-t p-3 text-center"><Button asChild variant="link"><Link to="/fax-tracker">View all activity →</Link></Button></div>}</div>}
