/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaxTrackerRouteImport } from './routes/fax-tracker'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaxTrackerRoute = FaxTrackerRouteImport.update({
  id: '/fax-tracker',
  path: '/fax-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fax-tracker': typeof FaxTrackerRoute
  '/patients': typeof PatientsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fax-tracker': typeof FaxTrackerRoute
  '/patients': typeof PatientsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fax-tracker': typeof FaxTrackerRoute
  '/patients': typeof PatientsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fax-tracker'
    | '/patients'
    | '/reports'
    | '/settings'
    | '/documents/$documentId'
    | '/patients/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fax-tracker'
    | '/patients'
    | '/reports'
    | '/settings'
    | '/documents/$documentId'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/fax-tracker'
    | '/patients'
    | '/reports'
    | '/settings'
    | '/documents/$documentId'
    | '/patients/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaxTrackerRoute: typeof FaxTrackerRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fax-tracker': {
      id: '/fax-tracker'
      path: '/fax-tracker'
      fullPath: '/fax-tracker'
      preLoaderRoute: typeof FaxTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
  }
}

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaxTrackerRoute: FaxTrackerRoute,
  PatientsRoute: PatientsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
